#!/usr/bin/env python3
"""
Génère un CSV d'éphéméride pour les 2 prochaines années :
- Saint(s) du jour (calendrier français)
- Journée(s) mondiale(s) / internationale(s) (ONU, UNESCO, OMS)
"""
import csv
from datetime import datetime, timedelta
from pathlib import Path

# --- Saints du jour (calendrier français, par mois/jour) ---
# Référence : calendrier romain / Nominis. Vide = pas de saint connu pour cette date.
SAINTS = {
    (1, 1): "Sainte Marie Mère de Dieu",
    (1, 2): "Saint Basile, Saint Grégoire de Nazianze",
    (1, 3): "Sainte Geneviève",
    (1, 4): "Sainte Odilon",
    (1, 5): "Saint Édouard",
    (1, 6): "Épiphanie",
    (1, 7): "Saint Raymond",
    (1, 8): "Saint Lucien",
    (1, 9): "Sainte Alix",
    (1, 10): "Saint Guillaume",
    (1, 11): "Saint Paulin",
    (1, 12): "Saint Tatien",
    (1, 13): "Sainte Yvette",
    (1, 14): "Saint Félix de Nole",
    (1, 15): "Saint Rémi",
    (1, 16): "Saint Marcel",
    (1, 17): "Saint Antoine le Grand",
    (1, 18): "Sainte Prisca",
    (1, 19): "Saint Marius",
    (1, 20): "Saint Sébastien",
    (1, 21): "Sainte Agnès",
    (1, 22): "Saint Vincent",
    (1, 23): "Saint Barnard",
    (1, 24): "Saint François de Sales",
    (1, 25): "Conversion de saint Paul",
    (1, 26): "Saint Timothée, Saint Titus",
    (1, 27): "Sainte Angèle",
    (1, 28): "Saint Thomas d'Aquin",
    (1, 29): "Saint Gildas",
    (1, 30): "Sainte Martine",
    (1, 31): "Saint Jean Bosco",
    (2, 1): "Sainte Ella",
    (2, 2): "Présentation du Seigneur",
    (2, 3): "Saint Blaise",
    (2, 4): "Sainte Véronique",
    (2, 5): "Sainte Agathe",
    (2, 6): "Saint Gaston",
    (2, 7): "Saint Eugène",
    (2, 8): "Sainte Jacqueline",
    (2, 9): "Sainte Apolline",
    (2, 10): "Saint Arnaud",
    (2, 11): "Notre-Dame de Lourdes",
    (2, 12): "Sainte Félice",
    (2, 13): "Sainte Béatrice",
    (2, 14): "Saint Valentin",
    (2, 15): "Saint Claude",
    (2, 16): "Sainte Julienne",
    (2, 17): "Saint Alexis",
    (2, 18): "Sainte Bernadette",
    (2, 19): "Saint Gabin",
    (2, 20): "Sainte Aimée",
    (2, 21): "Saint Pierre Damien",
    (2, 22): "Saint Pierre Damien",
    (2, 23): "Saint Lazare",
    (2, 24): "Saint Modeste",
    (2, 25): "Saint Roméo",
    (2, 26): "Saint Nestor",
    (2, 27): "Sainte Honorine",
    (2, 28): "Saint Romain",
    (2, 29): "Saint Auguste",
    (3, 1): "Saint Aubin",
    (3, 2): "Sainte Charles",
    (3, 3): "Saint Guénolé",
    (3, 4): "Saint Casimir",
    (3, 5): "Saint Olive",
    (3, 6): "Sainte Colette",
    (3, 7): "Saints Perpétue et Félicité",
    (3, 8): "Saint Jean de Dieu",
    (3, 9): "Sainte Françoise",
    (3, 10): "Saint Vivien",
    (3, 11): "Saint Constantin",
    (3, 12): "Saint Grégoire le Grand",
    (3, 13): "Sainte Rodrigue",
    (3, 14): "Sainte Mathilde",
    (3, 15): "Sainte Louise",
    (3, 16): "Sainte Bénédicte",
    (3, 17): "Saint Patrick",
    (3, 18): "Saint Cyrille de Jérusalem",
    (3, 19): "Saint Joseph",
    (3, 20): "Saint Herbert",
    (3, 21): "Saint Clément",
    (3, 22): "Sainte Léa",
    (3, 23): "Saint Victorien",
    (3, 24): "Sainte Catherine de Suède",
    (3, 25): "Annonciation",
    (3, 26): "Sainte Larissa",
    (3, 27): "Saint Rupert",
    (3, 28): "Saint Gontran",
    (3, 29): "Saint Gwenaël",
    (3, 30): "Saint Amédée",
    (3, 31): "Saint Benjamin",
    (4, 1): "Saint Hugues",
    (4, 2): "Saint François de Paule",
    (4, 3): "Saint Richard",
    (4, 4): "Saint Isidore",
    (4, 5): "Saint Vincent Ferrier",
    (4, 6): "Saint Marcellin",
    (4, 7): "Saint Jean-Baptiste de La Salle",
    (4, 8): "Saint Gautier",
    (4, 9): "Sainte Waudru",
    (4, 10): "Saint Fulbert",
    (4, 11): "Saint Stanislas",
    (4, 12): "Saint Jules",
    (4, 13): "Saint Martin Ier",
    (4, 14): "Saint Maxime",
    (4, 15): "Saint Paterne",
    (4, 16): "Saint Benoît-Joseph Labre",
    (4, 17): "Saint Anicet",
    (4, 18): "Saint Parfait",
    (4, 19): "Saint Léon IX",
    (4, 20): "Sainte Odette",
    (4, 21): "Saint Anselme",
    (4, 22): "Saint Alexandre",
    (4, 23): "Saint Georges",
    (4, 24): "Saint Fidèle",
    (4, 25): "Saint Marc",
    (4, 26): "Sainte Alida",
    (4, 27): "Sainte Zita",
    (4, 28): "Saint Louis-Marie Grignion de Montfort",
    (4, 29): "Sainte Catherine de Sienne",
    (4, 30): "Saint Robert",
    (5, 1): "Saint Joseph travailleur",
    (5, 2): "Saint Boris",
    (5, 3): "Saints Philippe et Jacques",
    (5, 4): "Sainte Sylvie",
    (5, 5): "Saint Irénée",
    (5, 6): "Saint Jean",
    (5, 7): "Sainte Gisèle",
    (5, 8): "Saint Désiré",
    (5, 9): "Sainte Pacôme",
    (5, 10): "Saint Antonin",
    (5, 11): "Sainte Estelle",
    (5, 12): "Saint Achille",
    (5, 13): "Notre-Dame de Fatima",
    (5, 14): "Saint Matthias",
    (5, 15): "Sainte Denise",
    (5, 16): "Saint Honoré",
    (5, 17): "Saint Pascal Baylon",
    (5, 18): "Saint Eric",
    (5, 19): "Saint Yves",
    (5, 20): "Saint Bernardin de Sienne",
    (5, 21): "Saint Constantin",
    (5, 22): "Sainte Julie",
    (5, 23): "Saint Didier",
    (5, 24): "Saint Donatien",
    (5, 25): "Saint Bède",
    (5, 26): "Saint Philippe Néri",
    (5, 27): "Saint Augustin de Cantorbéry",
    (5, 28): "Saint Germain",
    (5, 29): "Saint Gérald",
    (5, 30): "Sainte Jeanne d'Arc",
    (5, 31): "Visitation de la Vierge Marie",
    (6, 1): "Saint Justin",
    (6, 2): "Saints Marcellin et Pierre",
    (6, 3): "Saint Kévin",
    (6, 4): "Saint Clément",
    (6, 5): "Saint Boniface",
    (6, 6): "Saint Norbert",
    (6, 7): "Saint Gilbert",
    (6, 8): "Saint Médard",
    (6, 9): "Saint Ephrem",
    (6, 10): "Saint Landry",
    (6, 11): "Saint Barnabé",
    (6, 12): "Saint Guy",
    (6, 13): "Saint Antoine de Padoue",
    (6, 14): "Saint Élisée",
    (6, 15): "Sainte Germaine",
    (6, 16): "Saint Jean-François Régis",
    (6, 17): "Saint Hervé",
    (6, 18): "Saint Léonce",
    (6, 19): "Saint Romuald",
    (6, 20): "Saint Silvère",
    (6, 21): "Saint Louis de Gonzague",
    (6, 22): "Saint Alban",
    (6, 23): "Sainte Audrey",
    (6, 24): "Saint Jean-Baptiste",
    (6, 25): "Saint Prosper",
    (6, 26): "Saint Anthelme",
    (6, 27): "Saint Cyrille d'Alexandrie",
    (6, 28): "Saint Irénée",
    (6, 29): "Saints Pierre et Paul",
    (6, 30): "Premiers martyrs de Rome",
    (7, 1): "Saint Thierry",
    (7, 2): "Saint Martinien",
    (7, 3): "Saint Thomas",
    (7, 4): "Sainte Flore",
    (7, 5): "Saint Antoine-Marie Zaccaria",
    (7, 6): "Sainte Maria Goretti",
    (7, 7): "Saint Raoul",
    (7, 8): "Saint Thibault",
    (7, 9): "Sainte Amandine",
    (7, 10): "Saint Ulric",
    (7, 11): "Saint Benoît",
    (7, 12): "Saint Olivier",
    (7, 13): "Saint Henri",
    (7, 14): "Saint Camille",
    (7, 15): "Saint Vladimir",
    (7, 16): "Notre-Dame du Mont-Carmel",
    (7, 17): "Sainte Charlotte",
    (7, 18): "Saint Frédéric",
    (7, 19): "Saint Arsène",
    (7, 20): "Sainte Marina",
    (7, 21): "Saint Victor",
    (7, 22): "Sainte Marie-Madeleine",
    (7, 23): "Sainte Brigitte",
    (7, 24): "Sainte Christine",
    (7, 25): "Saint Jacques le Majeur",
    (7, 26): "Saints Anne et Joachim",
    (7, 27): "Saint Pantaléon",
    (7, 28): "Saint Samson",
    (7, 29): "Sainte Marthe",
    (7, 30): "Saint Pierre Chrysologue",
    (7, 31): "Saint Ignace de Loyola",
    (8, 1): "Saint Alphonse",
    (8, 2): "Saint Étienne Ier",
    (8, 3): "Sainte Lydie",
    (8, 4): "Saint Jean-Marie Vianney",
    (8, 5): "Notre-Dame des Neiges",
    (8, 6): "Transfiguration",
    (8, 7): "Saint Gaétan",
    (8, 8): "Saint Dominique",
    (8, 9): "Sainte Amour",
    (8, 10): "Saint Laurent",
    (8, 11): "Sainte Claire",
    (8, 12): "Sainte Clarisse",
    (8, 13): "Saint Hippolyte",
    (8, 14): "Saint Maximilien Kolbe",
    (8, 15): "Assomption",
    (8, 16): "Saint Roch",
    (8, 17): "Saint Hyacinthe",
    (8, 18): "Sainte Hélène",
    (8, 19): "Saint Jean Eudes",
    (8, 20): "Saint Bernard",
    (8, 21): "Saint Christophe",
    (8, 22): "Reine du Ciel",
    (8, 23): "Sainte Rose de Lima",
    (8, 24): "Saint Barthélemy",
    (8, 25): "Saint Louis",
    (8, 26): "Sainte Natacha",
    (8, 27): "Sainte Monique",
    (8, 28): "Saint Augustin",
    (8, 29): "Martyre de saint Jean-Baptiste",
    (8, 30): "Sainte Fiacre",
    (8, 31): "Saint Aristide",
    (9, 1): "Saint Gilles",
    (9, 2): "Sainte Ingrid",
    (9, 3): "Saint Grégoire le Grand",
    (9, 4): "Sainte Rosalie",
    (9, 5): "Sainte Raissa",
    (9, 6): "Saint Bertrand",
    (9, 7): "Sainte Reine",
    (9, 8): "Nativité de la Vierge Marie",
    (9, 9): "Saint Alain",
    (9, 10): "Saint Aubert",
    (9, 11): "Saint Adelphe",
    (9, 12): "Saint Apollinaire",
    (9, 13): "Saint Aimé",
    (9, 14): "Croix glorieuse",
    (9, 15): "Notre-Dame des Douleurs",
    (9, 16): "Saint Cyprien",
    (9, 17): "Saint Renaud",
    (9, 18): "Sainte Nadège",
    (9, 19): "Saint Janvier",
    (9, 20): "Saint Davy",
    (9, 21): "Saint Matthieu",
    (9, 22): "Saint Maurice",
    (9, 23): "Saint Constant",
    (9, 24): "Saint Silouane",
    (9, 25): "Saint Hermann",
    (9, 26): "Saints Côme et Damien",
    (9, 27): "Saint Vincent de Paul",
    (9, 28): "Saint Venceslas",
    (9, 29): "Saint Michel, Saint Gabriel, Saint Raphaël",
    (9, 30): "Saint Jérôme",
    (10, 1): "Sainte Thérèse de l'Enfant-Jésus",
    (10, 2): "Saints Anges gardiens",
    (10, 3): "Saint Gérard",
    (10, 4): "Saint François d'Assise",
    (10, 5): "Saint Fleur",
    (10, 6): "Saint Bruno",
    (10, 7): "Sainte Serge",
    (10, 8): "Sainte Pélagie",
    (10, 9): "Saint Denis",
    (10, 10): "Saint Ghislain",
    (10, 11): "Saint Firmin",
    (10, 12): "Saint Wilfried",
    (10, 13): "Saint Géraud",
    (10, 14): "Saint Calliste Ier",
    (10, 15): "Sainte Thérèse d'Avila",
    (10, 16): "Sainte Edwige",
    (10, 17): "Saint Ignace d'Antioche",
    (10, 18): "Saint Luc",
    (10, 19): "Saints Jean de Brébeuf et compagnons",
    (10, 20): "Sainte Adeline",
    (10, 21): "Sainte Céline",
    (10, 22): "Saint Jean-Paul II",
    (10, 23): "Saint Jean de Capistran",
    (10, 24): "Saint Florentin",
    (10, 25): "Saint Crépin",
    (10, 26): "Saint Dimitri",
    (10, 27): "Saint Émilien",
    (10, 28): "Saint Simon, Saint Jude",
    (10, 29): "Saint Narcisse",
    (10, 30): "Sainte Bienvenue",
    (10, 31): "Saint Quentin",
    (11, 1): "Toussaint",
    (11, 2): "Défunts",
    (11, 3): "Saint Hubert",
    (11, 4): "Saint Charles Borromée",
    (11, 5): "Sainte Sylvie",
    (11, 6): "Saint Léonard",
    (11, 7): "Saint Ernest",
    (11, 8): "Saint Geoffroy",
    (11, 9): "Dédicace de Saint-Jean-de-Latran",
    (11, 10): "Saint Léon le Grand",
    (11, 11): "Saint Martin",
    (11, 12): "Saint Christian",
    (11, 13): "Saint Brice",
    (11, 14): "Saint Sidoine",
    (11, 15): "Saint Albert le Grand",
    (11, 16): "Sainte Marguerite d'Écosse",
    (11, 17): "Sainte Élisabeth de Hongrie",
    (11, 18): "Dédicace des basiliques Saint-Pierre et Saint-Paul",
    (11, 19): "Sainte Mathilde",
    (11, 20): "Saint Edmond",
    (11, 21): "Présentation de la Vierge Marie",
    (11, 22): "Sainte Cécile",
    (11, 23): "Saint Clément",
    (11, 24): "Saint Florent",
    (11, 25): "Sainte Catherine d'Alexandrie",
    (11, 26): "Saint Conrad",
    (11, 27): "Saint Séverin",
    (11, 28): "Saint Jacques de la Marche",
    (11, 29): "Saint Saturnin",
    (11, 30): "Saint André",
    (12, 1): "Saint Florence",
    (12, 2): "Sainte Viviane",
    (12, 3): "Saint François Xavier",
    (12, 4): "Sainte Barbara",
    (12, 5): "Saint Gérald",
    (12, 6): "Saint Nicolas",
    (12, 7): "Saint Ambroise",
    (12, 8): "Immaculée Conception",
    (12, 9): "Saint Pierre Fourier",
    (12, 10): "Sainte Eulalie",
    (12, 11): "Saint Daniel",
    (12, 12): "Sainte Jeanne-Françoise de Chantal",
    (12, 13): "Sainte Lucie",
    (12, 14): "Saint Jean de la Croix",
    (12, 15): "Sainte Ninon",
    (12, 16): "Sainte Alice",
    (12, 17): "Saint Gaël",
    (12, 18): "Saint Gatien",
    (12, 19): "Saint Urbain V",
    (12, 20): "Saint Théophile",
    (12, 21): "Saint Pierre Canisius",
    (12, 22): "Sainte Françoise-Xavière",
    (12, 23): "Saint Armand",
    (12, 24): "Veillée de Noël",
    (12, 25): "Noël",
    (12, 26): "Saint Étienne",
    (12, 27): "Saint Jean l'Apôtre",
    (12, 28): "Saints Innocents",
    (12, 29): "Saint David",
    (12, 30): "Saint Roger",
    (12, 31): "Saint Sylvestre",
}

# --- Journées mondiales / internationales (ONU, UNESCO, OMS, etc.) ---
# Plusieurs journées peuvent tomber le même jour. Format: (mois, jour) -> liste de libellés.
WORLD_DAYS = {
    (1, 4): ["Journée mondiale du braille"],
    (1, 24): ["Journée internationale de l'éducation"],
    (1, 26): ["Journée internationale des énergies propres"],
    (1, 27): ["Journée internationale dédiée à la mémoire des victimes de l'Holocauste"],
    (1, 28): ["Journée internationale de la coexistence pacifique"],
    (2, 2): ["Journée mondiale des zones humides"],
    (2, 4): ["Journée internationale de la fraternité humaine"],
    (2, 6): ["Journée internationale de tolérance zéro à l'égard des mutilations génitales féminines"],
    (2, 10): ["Journée internationale du léopard d'Arabie", "Journée internationale des légumineuses"],
    (2, 11): ["Journée internationale des femmes et des filles de science"],
    (2, 12): ["Journée internationale pour la prévention de l'extrémisme violent"],
    (2, 13): ["Journée mondiale de la radio"],
    (2, 20): ["Journée mondiale de la justice sociale"],
    (2, 21): ["Journée internationale de la langue maternelle"],
    (3, 1): ["Journée mondiale des herbiers marins", "Journée Zéro discrimination"],
    (3, 3): ["Journée mondiale de la vie sauvage"],
    (3, 5): ["Journée internationale de sensibilisation au désarmement et à la non-prolifération"],
    (3, 8): ["Journée internationale des femmes"],
    (3, 10): ["Journée internationale des femmes juges"],
    (3, 15): ["Journée internationale de lutte contre l'islamophobie"],
    (3, 20): ["Journée internationale du bonheur", "Journée de la langue française", "Journée internationale de la Francophonie"],
    (3, 21): ["Journée internationale des forêts", "Journée mondiale des glaciers", "Journée internationale du Novruz", "Journée pour l'élimination de la discrimination raciale", "Journée mondiale de la poésie", "Journée mondiale de la trisomie 21"],
    (3, 22): ["Journée mondiale de l'eau"],
    (3, 23): ["Journée météorologique mondiale"],
    (3, 24): ["Journée pour le droit à la vérité", "Journée mondiale de la lutte contre la tuberculose"],
    (3, 25): ["Journée de solidarité avec les fonctionnaires détenus ou disparus", "Journée en mémoire des victimes de l'esclavage", "Journée internationale du zéro déchet"],
    (3, 30): ["Journée internationale du zéro déchet"],
    (4, 2): ["Journée mondiale de sensibilisation à l'autisme"],
    (4, 4): ["Journée internationale pour la sensibilisation aux mines"],
    (4, 5): ["Journée internationale de la conscience"],
    (4, 6): ["Journée internationale du sport au service du développement et de la paix"],
    (4, 7): ["Journée internationale de réflexion sur le génocide au Rwanda", "Journée mondiale de la santé"],
    (4, 12): ["Journée internationale du vol spatial habité"],
    (4, 14): ["Journée mondiale de la maladie de Chagas"],
    (4, 20): ["Journée de la langue chinoise"],
    (4, 21): ["Journée mondiale de la créativité et de l'innovation"],
    (4, 22): ["Journée internationale de la Terre nourricière"],
    (4, 23): ["Journée mondiale du livre et du droit d'auteur", "Journée de la langue anglaise", "Journée de la langue espagnole"],
    (4, 24): ["Journée des jeunes filles dans les TIC", "Journée internationale du multilatéralisme"],
    (4, 25): ["Journée mondiale du paludisme", "Journée internationale des délégués"],
    (4, 26): ["Journée internationale du souvenir de la catastrophe de Tchernobyl", "Journée mondiale de la propriété intellectuelle"],
    (4, 28): ["Journée mondiale pour la sécurité et la santé au travail"],
    (4, 29): ["Journée en mémoire des victimes des tremblements de terre"],
    (4, 30): ["Journée internationale du jazz"],
    (5, 1): ["Journée du Vesak (Bouddha)"],
    (5, 2): ["Journée mondiale du thon"],
    (5, 3): ["Journée mondiale de la liberté de la presse"],
    (5, 5): ["Journée mondiale de la langue portugaise"],
    (5, 8): ["Journées du souvenir et de la réconciliation (Seconde Guerre mondiale)"],
    (5, 11): ["Journée mondiale des oiseaux migrateurs"],
    (5, 12): ["Journée internationale de la santé des végétaux"],
    (5, 15): ["Journée internationale des familles"],
    (5, 16): ["Journée internationale de la lumière", "Journée internationale du vivre-ensemble en paix"],
    (5, 17): ["Journée mondiale des télécommunications et de la société de l'information"],
    (5, 19): ["Journée mondiale du fair-play"],
    (5, 20): ["Journée mondiale des abeilles"],
    (5, 21): ["Journée mondiale du thé", "Journée mondiale de la diversité culturelle"],
    (5, 22): ["Journée internationale de la diversité biologique"],
    (5, 23): ["Journée pour l'élimination de la fistule obstétricale"],
    (5, 24): ["Journée internationale du markhor"],
    (5, 25): ["Journée mondiale du football"],
    (5, 29): ["Journée internationale des Casques bleus"],
    (5, 31): ["Journée mondiale sans tabac"],
    (6, 1): ["Journée mondiale des parents"],
    (6, 3): ["Journée mondiale de la bicyclette"],
    (6, 4): ["Journée internationale des enfants victimes innocentes de l'agression"],
    (6, 5): ["Journée mondiale de l'environnement", "Journée internationale de la lutte contre la pêche illicite"],
    (6, 6): ["Journée de la langue russe"],
    (6, 7): ["Journée internationale de la sécurité sanitaire des aliments"],
    (6, 8): ["Journée mondiale de l'océan"],
    (6, 10): ["Journée internationale du dialogue entre les civilisations"],
    (6, 11): ["Journée internationale du jeu"],
    (6, 12): ["Journée mondiale contre le travail des enfants"],
    (6, 13): ["Journée internationale de sensibilisation à l'albinisme"],
    (6, 14): ["Journée mondiale du donneur de sang"],
    (6, 15): ["Journée mondiale de sensibilisation à la maltraitance des personnes âgées"],
    (6, 16): ["Journée internationale des envois de fonds familiaux"],
    (6, 17): ["Journée mondiale de la lutte contre la désertification et la sécheresse"],
    (6, 18): ["Journée internationale de la lutte contre les discours de haine", "Journée de la gastronomie durable"],
    (6, 19): ["Journée pour l'élimination de la violence sexuelle en temps de conflit"],
    (6, 20): ["Journée mondiale des réfugiés"],
    (6, 21): ["Journée internationale du Yoga", "Journée internationale de la célébration du solstice"],
    (6, 23): ["Journée internationale des veuves", "Journée des Nations Unies pour la fonction publique"],
    (6, 24): ["Journée internationale des femmes dans la diplomatie"],
    (6, 25): ["Journée des gens de mer"],
    (6, 26): ["Journée internationale contre l'abus et le trafic de drogues", "Journée pour le soutien aux victimes de la torture"],
    (6, 27): ["Journée internationale des personnes sourdaveugles", "Journée des micro-, petites et moyennes entreprises"],
    (6, 29): ["Journée internationale des tropiques"],
    (6, 30): ["Journée internationale des astéroïdes", "Journée internationale du parlementarisme"],
    (7, 6): ["Journée mondiale du développement rural", "Journée mondiale de la langue kiswahili"],
    (7, 11): ["Journée mondiale du cheval", "Journée mondiale de la population", "Journée de réflexion sur le génocide de Srebrenica"],
    (7, 12): ["Journée internationale de l'espoir", "Journée internationale de lutte contre les tempêtes de sable"],
    (7, 15): ["Journée mondiale des compétences des jeunes"],
    (7, 18): ["Journée internationale Nelson Mandela"],
    (7, 20): ["Journée internationale de la Lune", "Journée mondiale du jeu d'échecs"],
    (7, 25): ["Journée internationale des femmes et filles d'ascendance africaine", "Journée mondiale de prévention de la noyade"],
    (7, 28): ["Journée mondiale contre l'hépatite"],
    (7, 30): ["Journée internationale de l'amitié", "Journée mondiale contre la traite d'êtres humains"],
    (8, 6): ["Journée internationale des pays en développement sans littoral"],
    (8, 9): ["Journée internationale des peuples autochtones"],
    (8, 11): ["Journée mondiale du steel pan"],
    (8, 12): ["Journée internationale de la jeunesse"],
    (8, 19): ["Journée mondiale de l'aide humanitaire"],
    (8, 21): ["Journée internationale du souvenir des victimes du terrorisme"],
    (8, 22): ["Journée en mémoire des victimes de violences en raison de leur religion"],
    (8, 23): ["Journée internationale du souvenir de la traite négrière et de son abolition"],
    (8, 27): ["Journée mondiale des lacs"],
    (8, 29): ["Journée internationale contre les essais nucléaires"],
    (8, 30): ["Journée internationale des victimes de disparition forcée"],
    (8, 31): ["Journée internationale des personnes d'ascendance africaine"],
    (9, 5): ["Journée internationale de la charité", "Journée internationale des femmes et filles autochtones"],
    (9, 7): ["Journée internationale de la coopération policière", "Journée internationale de l'air pur"],
    (9, 8): ["Journée internationale de l'alphabétisation"],
    (9, 9): ["Journée pour la protection de l'éducation contre les attaques"],
    (9, 12): ["Journée des Nations Unies pour la coopération Sud-Sud"],
    (9, 15): ["Journée internationale de la démocratie"],
    (9, 16): ["Journée internationale de la protection de la couche d'ozone", "Journée internationale de la cardiologie interventionnelle"],
    (9, 17): ["Journée mondiale de la sécurité des patients"],
    (9, 18): ["Journée internationale de l'égalité de rémunération"],
    (9, 21): ["Journée internationale de la paix"],
    (9, 23): ["Journée internationale des langues des signes"],
    (9, 26): ["Journée mondiale de la mer", "Journée internationale pour l'élimination totale des armes nucléaires"],
    (9, 27): ["Journée mondiale du tourisme"],
    (9, 28): ["Journée internationale de l'accès universel à l'information"],
    (9, 29): ["Journée internationale de sensibilisation aux pertes et gaspillages de nourriture"],
    (9, 30): ["Journée internationale de la traduction"],
    (10, 1): ["Journée internationale des personnes âgées"],
    (10, 2): ["Journée internationale de la non-violence"],
    (10, 5): ["Journée mondiale des enseignants", "Journée mondiale du coton"],
    (10, 7): ["Journée mondiale de l'habitat"],
    (10, 9): ["Journée mondiale de la poste"],
    (10, 10): ["Journée mondiale de la santé mentale"],
    (10, 11): ["Journée internationale de la fille"],
    (10, 12): ["Journée mondiale des oiseaux migrateurs"],
    (10, 13): ["Journée internationale pour la réduction des risques de catastrophes"],
    (10, 15): ["Journée internationale des femmes rurales"],
    (10, 16): ["Journée mondiale de l'alimentation"],
    (10, 17): ["Journée internationale pour l'élimination de la pauvreté"],
    (10, 20): ["Journée mondiale de la statistique"],
    (10, 24): ["Journée des Nations Unies", "Journée mondiale d'information sur le développement"],
    (10, 27): ["Journée mondiale du patrimoine audiovisuel"],
    (10, 29): ["Journée internationale des soins et de l'assistance"],
    (10, 31): ["Journée mondiale des villes"],
    (11, 2): ["Journée internationale de la fin de l'impunité pour les crimes contre les journalistes"],
    (11, 5): ["Journée mondiale de sensibilisation aux tsunamis"],
    (11, 6): ["Journée pour la prévention de l'exploitation de l'environnement en temps de guerre"],
    (11, 10): ["Journée mondiale de la science au service de la paix et du développement"],
    (11, 14): ["Journée mondiale du diabète"],
    (11, 15): ["Journée mondiale du souvenir des victimes de la circulation routière"],
    (11, 16): ["Journée mondiale de la tolérance"],
    (11, 18): ["Journée mondiale pour la prévention et la guérison des violences sexuelles visant les enfants"],
    (11, 19): ["Journée mondiale des toilettes"],
    (11, 20): ["Journée de l'industrialisation de l'Afrique", "Journée mondiale de l'enfance"],
    (11, 21): ["Journée mondiale de la télévision", "Journée mondiale de la philosophie"],
    (11, 25): ["Journée internationale pour l'élimination de la violence à l'égard des femmes"],
    (11, 26): ["Journée mondiale des transports durables"],
    (11, 29): ["Journée internationale de solidarité avec le peuple palestinien"],
    (11, 30): ["Journée du souvenir des victimes de la guerre chimique"],
    (12, 1): ["Journée mondiale de lutte contre le sida"],
    (12, 2): ["Journée internationale pour l'abolition de l'esclavage"],
    (12, 3): ["Journée internationale des personnes handicapées"],
    (12, 4): ["Journée internationale des banques"],
    (12, 5): ["Journée internationale des volontaires", "Journée mondiale des sols"],
    (12, 7): ["Journée de l'aviation civile internationale"],
    (12, 9): ["Journée internationale contre la corruption", "Journée de commémoration des victimes du génocide"],
    (12, 10): ["Journée des droits de l'homme"],
    (12, 11): ["Journée internationale de la montagne"],
    (12, 12): ["Journée internationale de la couverture sanitaire universelle"],
    (12, 18): ["Journée de la langue arabe", "Journée internationale des migrants"],
    (12, 20): ["Journée internationale de la solidarité humaine"],
    (12, 21): ["Journée mondiale du basket-ball"],
    (12, 27): ["Journée internationale de la préparation aux épidémies"],
}


def get_saint(month: int, day: int) -> str:
    """Retourne le(s) saint(s) du jour, ou une chaîne vide si aucun."""
    return SAINTS.get((month, day), "")


def get_world_days(month: int, day: int) -> str:
    """Retourne les journées mondiales du jour, séparées par ' | ', ou une chaîne vide."""
    days = WORLD_DAYS.get((month, day), [])
    return " | ".join(days) if days else ""


def main():
    base_dir = Path(__file__).resolve().parent
    out_path = base_dir / "ephemeride_2ans.csv"
    start = datetime.now().date()
    end = start + timedelta(days=730)  # 2 ans

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f, delimiter=";")
        writer.writerow(["date", "saint", "journee_mondiale"])
        d = start
        while d <= end:
            saint = get_saint(d.month, d.day)
            world = get_world_days(d.month, d.day)
            writer.writerow([d.isoformat(), saint, world])
            d += timedelta(days=1)

    print(f"Fichier généré : {out_path}")
    print(f"Période : {start} → {end} ({730 + 1} jours)")


if __name__ == "__main__":
    main()
